seed: 0
seed_start: 0
seed_end: 1

defaults:
  - _self_
  - greedy_model: navi
  - sub_model: navi
  - coop_model: navi
  - train: sac
  - env: navigation

hydra:
  run:
    dir: results/${env.env_name}/${env.name}_${env.obs_type}/n${env.num_agents}_level${env.level}/${coop_model.name}_${now:%Y-%m-%d_%H-%M-%S}