env_name: "navigation"
name: 'continous'
is_discrete: False
num_agents: 2
num_items: 0
map_size: 128
max_vel: 0.03
min_vel: -0.01
max_ang_vel: 0.25
min_ang_vel: -0.25
max_acc: 0.015
max_ang_acc: 0.125
fov_r: 0.15
comm_r: 0.15
num_scans: 64
scan_range: 0.15
use_intentions: True
use_acc: False
level: 5
timeout: 100
rad: 0.02
goal_rad: 0.02
goal_reward: 3
crash_penalty: -10
time_penalty: -0.1
obs_type: "random"
sample_type: "uniform"
obs_size_lower_bound: 0.05
obs_size_upper_bound: 0.08