name: "fen"
algo: "sac"
agent_type: "sub"
is_discrete: False
num_sub_policy: 3
T: 5
gamma: 0.95
tau: 0.005
alpha: 0.2
hidden_dim: 256
msg_dim: 24
pos_dim: 2
fov_size: 100
actor_lr: 0.001
critic_lr: 0.001
alpha_lr: 0.001
batch_size: 256
save_interval: 20000
pos_type: traj
traj_length: 1
use_meta_policy: True
train_sub_policy: False
backup_entropy: True
auto_temp_tuning: True
# mask
mask_neighbor: True
mask_priority: False
r: 0.15
# train
horizon: 1000000
num_update: 30
update_interval: 1
num_collect_data: 100000
eval_interval: 250
eval_iters: 50
num_average_episodes: 500
render_interval: 1000
num_actors: 1
pretrain_iters: 7000
warmup_iters: 10000
# buffer
memory_size: 1500000
buffer_alpha: 0.6
beta_start: 0.4
beta_frames: 150000
use_per: False