name: "navi"
algo: "sac"
agent_type: "sub"
is_discrete: False
gamma: 0.95
tau: 0.005
alpha: 0.2
target_update_interval: 1
automatic_entropy_tuning: True
hidden_dim: 256
msg_dim: 24
pos_dim: 2
actor_lr: 0.001
critic_lr: 0.001
alpha_lr: 0.001
batch_size: 256
save_interval: 20000
fov_size: 100
backup_entropy: True
use_jax: True
auto_temp_tuning: True
pos_type: traj
traj_length: 1
use_meta_policy: False
use_trained_model: False
train_sub_policy: False
stop_rate: 0.03
# mask
mask_neighbor: True
mask_priority: False
r: 0.15
# buffer
buffer_alpha: 0.6
beta_start: 0.4
beta_frames: 100000
use_per: False
# train
horizon: 1000000
update_interval: 1
memory_size: 200000
num_collect_data: 100000
eval_interval: 250
eval_iters: 50
num_average_episodes: 500
render_interval: 1000
num_actors: 1
pretrain_iters: 7000
warmup_iters: 10000
