name: "fen"
algo: "sac"
agent_type: "meta"
is_discrete: True
gamma: 0.95
tau: 0.005
alpha: 0.2
hidden_dim: 256
msg_dim: 24
num_sub_policy: 3
pos_dim: 2
action_dim: 4
actor_lr: 0.00001
critic_lr: 0.00001
alpha_lr: 0.00001
batch_size: 256
save_interval: 20000
pos_type: traj
traj_length: 1
use_meta_policy: True
train_sub_policy: False
coop_beta: 0.5
# mask
mask_neighbor: True
r: 0.15
# train
horizon: 500000
num_update: 30
update_interval: 1
num_collect_data: 100000
eval_interval: 250
eval_iters: 50
num_average_episodes: 500
render_interval: 1000
num_actors: 1
pretrain_iters: 7000
# buffer
memory_size: 1500000
buffer_alpha: 0.6
beta_start: 0.4
beta_frames: 100000
use_per: False